# Publish Docker Container By GitHub Actions
# Build, test, and push Docker image to GitHub Packages.

name: Publish Docker Container

on:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/vinodpandhare/project-byvp:latest
            ghcr.io/vinodpandhare/project-byvp:${{ github.sha }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Use Node.js version 20

      - name: Install dependencies
        run: npm install  # Change if using a different package manager

      - name: Run app.js
        run: npm app  # Adjust to your application's start command

      - name: Announce success
        if: success()
        run: echo "Docker image built, tested, and pushed successfully!"
